### ISSUE TITLE
Combining Films and Series Into One Library

### ISSUE THREAD

**Issue by Lazmarr** [Dingmatt/AMSA#10]
Is this possible with AMSA?
I cannot figure out how to get it to work correctly.
Any help with this is appreciated.

**Comment by Dingmatt** [comment]
Hi @Lazmarr,

I'm afraid that AMSA can't currently retrieve metadata for films, its on the backlog but won't be attempted until the rest of the processes are working as expected.

If you need a agent which can do both then I'd recommend [HAMA](https://github.com/ZeroQI/Hama.bundle) for the time being.

**Comment by Jopo-JP** [comment]
Is there any update?
