### ISSUE TITLE
AniDB blocked generic useragents

### ISSUE THREAD

**Issue by Konack** [Dingmatt/AMSA#11]
Roughly a week ago from this post AniDB blocked generic useragents which causes this to stop functioning. There is a thread discussing this for HAMA which should give some insight as to what's going on here https://github.com/ZeroQI/Hama.bundle/issues/309

**Comment by Dingmatt** [comment]
Sorry for the long wait, I've just started to redevelop parts of this agent.

This is now corrected in v0.1.5 along with a few other issues
