### ISSUE TITLE
ITA Support

### ISSUE THREAD

**Issue by NinjaGundam** [Dingmatt/AMSA#13]
Hello, this plug-in is great to find all things on folders, but i have on in ITAlian folder structure..
Mainly the problem is with SEASON 1,2,3 etc in italian translated to STAGIONE 1,2,3
Is it possbile to add a multilanguage\additional string to seatch seasons even in those folders ?
Thx in advance

Chooo

**Comment by Dingmatt** [comment]
Hi NinjaGundam,

I've gone ahead and added STAGIONE to the whitelist of season folders' names, this will be included in future releases but you can easily patch the file but overwriting the 'Plex Media Server\Scanners\Series\Absolute Series Scanner.py' with the one in the zip attached.

[Absolute Series Scanner.zip](https://github.com/Dingmatt/AMSA/files/4583630/Absolute.Series.Scanner.zip)

**Comment by NinjaGundam** [comment]
**Glad to hear, many thx for this!!!**

There is another thing that bug me..  when you have anime season, op\ed and oav..
Having Season 0 displayed in plex with inside (OP\ED\Oav Movies) is bad.
Isn't there a way to put OP\ED\Extra with label "Extra" instead to put all in Season 0 ?
Would be nice to have each folder on plex for everysingle OAV or if you have more OAV like 1,2,3
u we have to rename them OAV 1 - S0E1, OAV 2 - S0E2, OAV 3 - S0E3;
and even more complicated if you have more OAV and every one of them is composed of more part.

OAV1 (2 episodes)
OAV1 - S0E1
OAV1-  S0E2

OAV2 (3 episodes)
OAV2 - S0E3
OAV2 - S0E4
OAV2 - S0E5

Sorry for my english but i hope to made you understand.
Taking for example "Slayers" anime serie, it was such a mess to make it on Plex ^_^;
Let me know if I can help testing etc.


Chooo

**Comment by Dingmatt** [comment]
Hi NinjaGundam,

I'm afraid that's outside the scope of this plugin, which is designed as an anime meta agent for the existing Plex folder structure. If you're interested in a custom structure then I can recommend [HAMA](https://github.com/ZeroQI/Hama.bundle), which has many of the same features as ASMA but also deals with custom folders.
