### ISSUE TITLE
AMSA plug-in not showing in the agents panel

### ISSUE THREAD

**Issue by eslamsidereel** [Dingmatt/AMSA#14]
I love this plugin. I have been using it for two years now, but after updating PMS to latest version 1.19.2.2737, amsa wont show up in the agents panel. I tried a fresh install but no luck.
this is my log file.
[Plex Media Server.log](https://github.com/Dingmatt/AMSA/files/4576314/Plex.Media.Server.log)

I don't know what's the problem. I hope you can help me fix this issue.

**Comment by Dingmatt** [comment]
Hi Eslam,

I think I've spotted the issue and have released a [hotfix](https://github.com/Dingmatt/AMSA/releases/tag/v1_0_1).

I'd advise trying to update to v1.01 and seeing if that corrects the issue, please ensure you also remove the 'Amsa_Test.bundle' folder from the plugins folder as it might cause a conflict.

When updating from the demo versions then be prepared for a full library refresh, though if you'd rather avoid this then you'll need to rename the 'com.plexapp.agents.amsa_test' folder in the '\Plug-in Support\Caches' to 'com.plexapp.agents.amsa'.

**Comment by eslamsidereel** [comment]
Thank you for replying.
I installed v1.01, made sure to delete 'Amsa_Test.bundle' folder from the plugins folder and made sure that 'com.plexapp.agents.amsa' is correctly named in '\Plug-in Support\Caches', But the issue still persist .
Here the log after installing v1.01
[Plex Media Server.log](https://github.com/Dingmatt/AMSA/files/4583703/Plex.Media.Server.log)
![01](https://user-images.githubusercontent.com/45595948/81118379-05164c80-8f29-11ea-9ddb-6092a6e3e01a.jpg)
![02](https://user-images.githubusercontent.com/45595948/81118382-06477980-8f29-11ea-94c2-486791321715.jpg)
![03](https://user-images.githubusercontent.com/45595948/81118387-06e01000-8f29-11ea-8a6a-6b1165135c08.jpg)

**Comment by Dingmatt** [comment]
Hi Eslam,

It seems your AMSA install isn't starting for some reason, would you mind sending me your 'com.plexapp.agents.amsa.log' file, found at 'Plex Media Server\Logs\PMS Plugin Logs'.

I'll see if that can shine any light on the issue.

**Comment by eslamsidereel** [comment]
Here is my AMSA log file.
[com.plexapp.agents.amsa.log](https://github.com/Dingmatt/AMSA/files/4604311/com.plexapp.agents.amsa.log)

**Comment by Dingmatt** [comment]
Hi Eslam,

Thank you for that log, it's helped me diagnose the issue. Please try this [hotfix](https://github.com/Dingmatt/AMSA/releases/tag/v1_0_2), it should correct the problem.

**Comment by eslamsidereel** [comment]
Thank you very much. 😍 The hotfix 1.0.2 solved the issue. Amsa showed up in the agents folder. I am now resuming rebuilding my anime library.
