### ISSUE TITLE
AMSA not populating metadata.

### ISSUE THREAD

**Issue by myhe01** [Dingmatt/AMSA#16]
[Plex Media Scanner.log](https://github.com/Dingmatt/AMSA/files/5087294/Plex.Media.Scanner.log)
[com.plexapp.system.log](https://github.com/Dingmatt/AMSA/files/5087295/com.plexapp.system.log)

Please forgive me, as I was only able to find two of the required six logs.

![image](https://user-images.githubusercontent.com/28101069/90454153-6b7e3f80-e0c0-11ea-81de-205dc76c7b6b.png)
(I didn't see a `Logs` directory).

ASS seems to be working right. It recognizes series, regardless of if "[anidb-xxxxx]" is included in the directory name. AMSA doesn't seem to be populating any metadata, though.

![image](https://user-images.githubusercontent.com/28101069/90454282-b8621600-e0c0-11ea-8a74-c4be0e73bbb1.png)

I was having this same issue with HAMA, and figured I'd try AMSA to see if it would work before I worked more at solving it. Of course, I've tried deleting, restarting Plex, and recreating the library. I used cd -R commands to copy AMSA and co. into the right directories.

![image](https://user-images.githubusercontent.com/28101069/90454441-4211e380-e0c1-11ea-93dc-4fd03a4aab38.png)
![image](https://user-images.githubusercontent.com/28101069/90454461-4f2ed280-e0c1-11ea-95fe-3aa8900fe0a9.png)

**Comment by Dingmatt** [comment]
Hi @myhe01,

I believe I've tracked down the issue, please try the latest [hotfix](https://github.com/Dingmatt/AMSA/releases/tag/v1_0_3) and see if that correct your issue.

Regards,
