### ISSUE TITLE
Using AMSA with other plugins

### ISSUE THREAD

**Issue by mokin009x** [Dingmatt/AMSA#18]
Hi AMSA solves a lot of problems for me compared to what I previously used for my anime library. But I have just one problem/Request. If possible I Would like ASMA to be able to use Sub Zero the Subtitle plugin. Because that plugin extracts embedded subtitles for me and converts them to .srt files. that's what I need. 

this problem is hard to explain in words so I will include 2 pictures.

![pic1](https://user-images.githubusercontent.com/35726400/93023987-18ca7180-f5f3-11ea-913f-a3a38f26d080.png)

![pic2](https://user-images.githubusercontent.com/35726400/93023994-24b63380-f5f3-11ea-8f2d-7bfc01f97192.png)

The first picture shows AMSA.
The second picture shows my previous agent.

The problem is that I don't know how I can add sub-zero to the AMSA list. if you or anyone can help I would appreciate it

**Comment by Dingmatt** [comment]
Here's the steps you'll need follow to add SubZero:

1. Browse to the AMSA Code directory (\Plug-ins\Amsa.bundle\Contents\Code)
1. Open '`__init__.py`' in a text editor
1. On line 35 you'll find the following:
`accepts_from = ["com.plexapp.agents.localmedia"]`
Change it to:
`accepts_from = ["com.plexapp.agents.localmedia","com.plexapp.agents.subzero"]`
**warning the file's syntex sensitive, the spaces and structure are all very specific, add the extra subzero part without changing anything else**
1. Restart Plex and you should see the extra SubZero option

Hope this helps

**Comment by mokin009x** [comment]
Yes, this fixed thank you so much.
