### ISSUE TITLE
Add helpful example to installation section of README

### ISSUE THREAD

**Issue by chudkins** [Dingmatt/AMSA#20]
Step 2 says, "Place the content of the zip into your Plex Media Server directory."  For someone who has never installed a third-party agent before, this is not clear enough and could easily be mistaken for the program's installation directory.  I suggest amending this to be more like your Reddit post from a few years back, where you gave the actual location.

I propose something like this:
> Place the content of the zip into your Plex Media Server directory.  On Windows, that would be: `%LOCALAPPDATA%\Plex Media Server`

**Comment by Dingmatt** [comment]
While I'd like to be more specific, it'd ultimately be unhelpful to specify a particular path as is completely depends directory selected during installation
