### ISSUE TITLE
Issue when matching OVA

### ISSUE THREAD

**Issue by entisocial** [Dingmatt/AMSA#22]
Hello, I have several series that also have OVA and weird things happen, for instance I have 2 folders for 2 entries:
- Hyouka
- Hyouka Motsubeki Mono wa

The second one is an OVA.
If I try to match or fix match the OVA with its proper anidb entry it will get renamed as Hyouka (instead of Hyouka: Motsubeki Mono wa) but is still separated from the main Hyouka (as it should). The OVA and the main series will then share the same poster and the same description however the episodes titles are good (the OVA is not seen as episode 1 of the main series, it has the right episode title). So am I missing something?
I've noticed that both OVAs have colons in their titles, could it be that something just stops when it detects ":" and just cut the end of the titles?

**Comment by Dingmatt** [comment]
As AMSA follows the Plex series structures (almost identical to TVDB), the Hyouka Motsubeki Mono wa (aka Hyouka: What Should Be Had) OVA isn't considered a series in its own right; it's episode 11.5, though as far as Plex is concerned it's the Hyouka Special #1.

You've two options:
1. Use the Anidb entry and manually rename the extra series / choose a different poster (it's not how AMSA's designed but it'll work)
2. Create a specials folder inside Hyouka and use the "S00E01" naming scheme for the OVA.

If you go with the second then it'll look something like this

      /Anime Shows
         /Hyouka 
            /Season 1
               Hyouka  - S01E01 - The Return of the Time-Honored Classic Lit Club
            /Specials
               Hyouka - S00E01 - What Should Be Had

Hope this helps
