### ISSUE TITLE
There is no agent to select

### ISSUE THREAD

**Issue by foxmajik** [Dingmatt/AMSA#27]
I can select scanner to "Absolute Series Scanner" but after that the only options for agent are:

Personal Media Shows
TheTVDB
Plex TV Series
The Movie Database

I followed all of the instructions in the readme and restarted the server.

**Comment by winceptor** [comment]
I noticed same issue, but when i added yet another agent it suddenly appeared. Maybe try restarting plex a few times.

**Comment by foxmajik** [comment]
It eventually started showing up after a couple of restarts, but then the agent destroyed my library by replacing hundreds of shows and movies I had already set correct metadata for with obscure, wrong Japanese movie and show titles and metadata.

So I pretty obviously removed it and rolled back my database.

Note to self: Only use this agent for libraries that only contain japanese content.
