### ISSUE TITLE
AMSA not being loaded (Plex 1.25.1.5286 Ubuntu Linux x64 20.04 LTS)

### ISSUE THREAD

**Issue by lavavex** [Dingmatt/AMSA#28]
AMSA doesnt work with clean plex install on linux. logs indicate the plugin times out or errors out causing plex to stop the plugin
[Plex Logs.zip](https://github.com/Dingmatt/AMSA/files/7701253/Plex.Logs.zip)
.

**Comment by n0v3xx** [comment]
@Dingmatt Is that plugin here dead?
And how can i install it? There a few folders under /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/ ...

**Comment by Dingmatt** [comment]
Hi Lavavex,

I don't run the plugin on linux myself but looking at the log it seems you're suffering from a permissions issue. You'll need to makes sure that plex has access privilages to it's own directories, for AMSA that's specifically '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.amsa'.

Regards,
