### ISSUE TITLE
Posters and banners cannot be loaded

### ISSUE THREAD

**Issue by BinXia** [Dingmatt/AMSA#29]
AMSA is a wonderful plug-in for PLEX and I really appreciate the contribution of the authors. 
However, I'm wondering if posters and banners of animes cannot be pulled from aniDB (only titles work). Is this problem with my network connection or the API of aniDB?

**Comment by BinXia** [comment]
![QQ20220205-163711](https://user-images.githubusercontent.com/8417171/152634949-ebb0cf7c-c011-45fc-85fb-326a08794db9.png)
)

**Comment by Dingmatt** [comment]
Hi BinXia,

Most aniDB issues are simply a temporary soft-ban from the API, this can happen if you add a large library all at once or share an IP with other users. Though it's not a big issue, just wait 24 hours and try refreshing the metadata for the series affected.

If it's a large number of series then you can tell plex to refresh the metadata for that entire library, AMSA is smart enough to avoid refreshing any series it has already cached.

Regards,
