### ISSUE TITLE
Amsa.bundle deleted by plex on start

### ISSUE THREAD

**Issue by Echizen67100** [Dingmatt/AMSA#30]
Hi, on windows 10 when i start plex the Amsa.bundle directory is deleted. How can i do ?

Thanks and have a nice day.

**Comment by Dingmatt** [comment]
Hi Echizen67100,

I'm afraid that's not normal behaviour, the best I could advise is to check it's installed into the correct directory (should be in 'Plex Media Server\Plug-ins\Amsa.bundle'). If it is then there must be something else on your system that's causing the problem.

Regards,
