### ISSUE TITLE
Metadata and posters are not loaded

### ISSUE THREAD

**Issue by golddragon007** [Dingmatt/AMSA#31]
When now I place a new series or I have an old series it does not fill the metadata information and doesn't download the posters, it detects the anime, I see the AniDB ID after the title, but nothing else happens.

Plex version: 1.25.6.5577
Addon version: 1.06

i.e.
Hakozume: Kouban Joshi no Gyakushuu [anidb-16503]
Fantasy Bishoujo Juniku Ojisan to [anidb-16325]

**Comment by Dingmatt** [comment]
Are you still having an issue, on the surface this sounds like a soft anidb IP ban. They usually wear off after 24 hours and are caused by large library refreshes

**Comment by golddragon007** [comment]
Ehh, well I have the
Xian Wang De Ri Chang Sheng Huo 2 [anidb-16352]
but I think that's normal as I can't see it on the DB. But yes, probably it was a ban. Can be a queue implemented so the device won't be banned? (this can solve the issue, but it will work only if plex can have cron job like feature)

**Comment by averycooke** [comment]
I had the same behavior, and can confirm that it was a ban as verified by trying the request in my browser. 
Script appears to already be aware of banning and logs indicate that it does delay in attempt to avoid it. 

 `INFO (functions:33) - Functions - XMLFromURL() - AniDB AntiBan Delay: 2022-07-14 16:40:30.077739`
`DEBUG (functions:112) - Functions - XMLFromURL() - Not an XML file, AniDB banned possibly,`

**Comment by Dingmatt** [comment]
I've experimented with a cron-like data refresh process in the past but to no avail, after a certain amount of data the anidb API just seems to soft-ban regardless of the duration between calls
