### ISSUE TITLE
scanner isn't auto detecting additions to the filesystem

### ISSUE THREAD

**Issue by CommanderBubble** [Dingmatt/AMSA#34]
when new episodes are added to an existing series, the scanner doesn't auto-detect them, and you have to select "Scan Library Files" on the library for the missing files to get added

**Comment by Dingmatt** [comment]
Hi,

It sounds like you're having a issue with Plex itself, probably file permissions, as the scanner inside AMSA is triggered by the application.

If running it manually works as expected but it doesn't autorun, then it has to be a overall Plex issue.

Sorry I couldn't be of more help
