### ISSUE TITLE
deleted series aren't removed from the library

### ISSUE THREAD

**Issue by CommanderBubble** [Dingmatt/AMSA#35]
after removing a series from the filesystem, the library doesn't detect that it has been removed and remove the corresponding show(s). this persists even after a server reboot and a performign "Scan Library Files" and "Empty Trash" on the library manually

**Comment by Dingmatt** [comment]
Hi,

It sounds like you're having a issue with Plex itself, probably file permissions, as the scanner inside AMSA is triggered by the application.

If running it manually works as expected but it doesn't autorun, then it has to be a overall Plex issue.

Sorry I couldn't be of more help
