### ISSUE TITLE
shows showing up twice

### ISSUE THREAD

**Issue by SatanSOF2** [Dingmatt/AMSA#37]
hi, im new to using this, so i was curious why my shows were showing up 2 times, with one saying the seasons underneath and the other saying show.....  am i doing something wrong? thx in advanced.

![image](https://user-images.githubusercontent.com/91221677/194189738-fbbc205b-c664-4daf-be38-9c9fd0f06d41.png)

**Comment by Dingmatt** [comment]
Hi,

I'm not entirely sure what's going on there but it's probably a collection issue, the "Log Horizon" is the show and the "Log Horizon (2014) is a collection which contains that show.

I'd advise changing your library setting to hide collections by default, you can always view them from the collections tab if you need to.

![image](https://user-images.githubusercontent.com/14905596/194408839-69274e1f-25c0-4d4a-8778-98b9cd90837e.png)

Regards,

**Comment by SatanSOF2** [comment]
ohh thank you, i cant believe i missed that option ><
