### ISSUE TITLE
No Posters Coming Up

### ISSUE THREAD

**Issue by KennyWongX** [Dingmatt/AMSA#43]
I just spun up a new Win Server 2022 yesterday
Installed Plex Media Server
Resetup the Scanner and Agent
I believe it's pulling the metadata and organizing/naming correctly but none of the posters are showing up

I've readded the library several times
Refreshed Metadata multiple times
Empty, Optimize, Clean

[com.plexapp.agents.amsa.log](https://github.com/Dingmatt/AMSA/files/11253886/com.plexapp.agents.amsa.log)
[com.plexapp.system.log](https://github.com/Dingmatt/AMSA/files/11253887/com.plexapp.system.log)
[Plex Media Scanner (custom ASS) - filelist.log](https://github.com/Dingmatt/AMSA/files/11253888/Plex.Media.Scanner.custom.ASS.-.filelist.log)
[Plex Media Scanner (custom ASS).log](https://github.com/Dingmatt/AMSA/files/11253889/Plex.Media.Scanner.custom.ASS.log)

**Comment by KennyWongX** [comment]
Found reason for issue
https://github.com/ZeroQI/Hama.bundle/issues/547

"One of the undocumented changes Plex made with 1.32.X is [they dropped OpenSSL 1.1.1 support](https://forums.plex.tv/t/ssl-became-broken-after-latest-pms-update/837416/4), so now it's OpenSSL 3+ only. It really sucks because Plex uses Python 2.7 which doesn't have OpenSSL 3. I've asked about any plans to include python3 but worried that this might be the end of plugins."

**Comment by Dingmatt** [comment]
Thank you for brining this to my attention, I'll take a look into it. It's strange as things continue to work for all my tests, but I can see the same errors being generated

**Comment by Dingmatt** [comment]
@KennyWongX Which data sources have you enabled (AniDb, TVDB, etc?)

**Comment by Dingmatt** [comment]
Hi @KennyWongX,

My theory was correct, I've included a fix in the latest [1.0.7.3 hotfix](https://github.com/Dingmatt/AMSA/releases/tag/V1_0_7_3), this version will use a little more bandwidth (and storage) when refreshing metadata but it's the only workaround until Plex fixes it their side.
