### ISSUE TITLE
i dont see anything

### ISSUE THREAD

**Issue by lamolosau** [Dingmatt/AMSA#44]
![image](https://github.com/Dingmatt/AMSA/assets/101528190/28dc6e29-e065-44a6-ad3b-cbcc0afa2045)

**Comment by Dingmatt** [comment]
Hi,

I've seen this issue before, it seems to be a permissions issue. The anime list is downloaded (and cached for a certain time) during the plugins startup, please try the following

1. Go to 'Plex Media Server\Plug-in Support\Data\com.plexapp.agents.amsa\DataItems\Cache' and delete the following files: 
- anime-titles
- anime-list-master.xml

2. Restart your plex instance.
3. Try fixing the match / refreshing the metadata.

The list is downloaded from the following github repository 'https://raw.githubusercontent.com/Anime-Lists/anime-lists/master/' so you'll need to ensure your system has access to that (no firewall rules, etc).
