### ISSUE TITLE
Wrong metadata

### ISSUE THREAD

**Issue by Saph1s** [Dingmatt/AMSA#45]
**Issue:**

When I try to match data, I get the wrong result.
For example, I try to match anidb-15593 anime, but instead it uses data from anidb-11370
![image](https://github.com/Dingmatt/AMSA/assets/60987685/97edaeca-d23b-487e-871c-85f3ec48be91)

**Logs:**

[Plex Media Scanner (custom ASS).log](https://github.com/Dingmatt/AMSA/files/11646803/Plex.Media.Scanner.custom.ASS.log)
[com.plexapp.agents.amsa.log](https://github.com/Dingmatt/AMSA/files/11646804/com.plexapp.agents.amsa.log)
[com.plexapp.system.log](https://github.com/Dingmatt/AMSA/files/11646805/com.plexapp.system.log)
[Plex Media Scanner (custom ASS) - filelist .log](https://github.com/Dingmatt/AMSA/files/11646806/Plex.Media.Scanner.custom.ASS.-.filelist.log)

**Comment by Dingmatt** [comment]
Hi Saph1s, AMSA is working as intended. It is designed to mimic the standard Plex/TVDB show structure, so Re:Zero - Starting Life in Another World 2nd Season Part 2 (anidb-15593) will show as a season of Re:Zero - Starting Life in Another World (anidb-11370).

**Comment by Saph1s** [comment]
> Re:Zero - Starting Life in Another World 2nd Season Part 2 (anidb-15593) will show as a season of Re:Zero - Starting Life in Another World (anidb-11370).

But the episodes are misidentified and the titles and images from the first season (anidb-11370) are used. While the first part of the second season is correctly detected (anidb-14792).

![image](https://github.com/Dingmatt/AMSA/assets/60987685/848b9468-31bd-4280-9bd7-88a12ce0a359)
![image](https://github.com/Dingmatt/AMSA/assets/60987685/30416906-9d7f-40ec-aea9-b1afb991fb8a)

**Comment by Dingmatt** [comment]
In that case it's likely also the way your files are structured. The AniDB standard (storing the show as a seperate folder) is still in testing, AMSA was designed to mimic the TVDB standard that Plex already uses (as a season folder of the existing show).

I'll start running more tests on the ANIDB standard to get it sorted asap.
