### ISSUE TITLE
Incorrect match even when selecting proper match

### ISSUE THREAD

**Issue by WrayOfSunshine** [Dingmatt/AMSA#48]
So I'm trying to add https://anidb.net/anime/17652 to my Plex server, but it's incorrectly being flagged as the first season, no matter what I do. I've even gone into "fix match" and tried to manually reselect it, to no avail.

Screenshot verifying the match is to the right anidb entry.

Any ideas on what I can do to fix this?

![image](https://github.com/Dingmatt/AMSA/assets/14261370/73b93418-4468-4d51-989a-0021a5f8e0cd)

**Comment by Dingmatt** [comment]
Hi dethmourne, AMSA is working as intended. It is designed to mimic the standard Plex/TVDB show structure, so Is It Wrong to Try to Pick Up Girls in a Dungeon? IV (anidb-17652) will show as a season of Is It Wrong to Try to Pick Up Girls in a Dungeon? (anidb-10894).
