### ISSUE TITLE
AMSA plug in does not start

### ISSUE THREAD

**Issue by moxz** [Dingmatt/AMSA#5]
Hi I would like to help to try out this plugin but I can't get it to work with MY PMS on Ubuntu
Here is my log for the plugin https://pastebin.com/g8V4X195

**Comment by Dingmatt** [comment]
@moxz This seems to be the same issue reported as the one found here:
[https://github.com/Dingmatt/AMSA/issues/4](https://github.com/Dingmatt/AMSA/issues/4)

I'm going to merge both tickets and work on it now, it seems one of the proxy API's have changed so the agents code needs updating.
