### ISSUE TITLE
HAMA or AMSA 

### ISSUE THREAD

**Issue by Snake3y3s** [Dingmatt/AMSA#53]
So there is both the HAMA plex agent and the AMSA plex agent... as far as I understand, the AMSA agent uses the HAMA agent AND TVDB.
So what is the point of having HAMA then?

Or can I install both or is it unnecessary?
I,E. if AMSA uses more sources and includes HAMA, then why would I use HAMA?

**Comment by Dingmatt** [comment]
AMSA uses a modified version of the HAMA file scanner, not the HAMA agent itself. Rule of thumb, if you'd like something that follows the standard Plex series logic (TVDB style) then use AMSA, if you'd like more control over your library or want to mix in movies without them being 'specials' of a series, then use HAMA.

Both work in similar ways but structure your library differently.
