### ISSUE TITLE
Agent finds the right reference, then gets the wrong data!

### ISSUE THREAD

**Issue by Daimonin** [Dingmatt/AMSA#54]
Is this project still alive? Anyone here other then lost souls?

I'm having an issue with this agent.

When the metdata is wrong, and I go do Fix Match, it finds the right item, I confirm it with Anidb ID, click on it... it pulls metadata and... nothing changes. Still the same wrong image, name, everything! WTF mate?

Example: I have Evangelion 1.11 (Anidb 4847). But it's showing as the old Evangelion.
I Fix Match, and it successfully identifies it as AniDB 4847.
But doesn't change anything!

It's been happening with pretty much every show that gets matched wrong. The Agent is great when it works, which yes, is most of the time, but absolutely useless when trying to FIX a mistake. Pretty much have to just redo all the metadata by hand each time.

Also, it would be swell if it stopped creating 1 item Collections. Please just leave collection creation to the user, since the agent can't recognize that a show with 1 item doesn't need a collection! Or even 0 item collections.

**Comment by Dingmatt** [comment]
Hi Daimonin, AMSA is working as intended. It is designed to mimic the standard Plex/TVDB show structure, so Evangelion: 1.0 You Are (Not) Alone (anidb-4847) will show as special 3 (S00E03) of Neon Genesis Evangelion (anidb-22).

**Comment by Daimonin** [comment]
Hey thanks, I'll have to keep trying to get it right then. My folder structure and or file names must be messed up then. Cause it's just showing up as anidb-22 episode 1.

**Comment by Dingmatt** [comment]
What's the name of the file? I'll see if I can recreate it and advise.

**Comment by Daimonin** [comment]
I fixed my folder structure and everything is working much better now. Realizing it's mimicing TVDB stucture helped with finding the right file names. Everything except for One Piece [anidb-69] and Utawarerumono Utawarerumono [anidb-3427] have images and metadata pulled from aniDB now. THose two haven't populated in two days for some reason, though they are recognized.

Not sure whats going on there, but I think it's a Plex issue rather then AMSA.

**Comment by Dingmatt** [comment]
Due to the size one One Piece and rebuilding your metadata you've probably been hit by a 24 hour API ban from AniDB. Give it 48 hours and refresh the series, that'll sort it.
