### ISSUE TITLE
How to handle special for different seasons?

### ISSUE THREAD

**Issue by cokebar** [Dingmatt/AMSA#6]
E.G:
Season 1,2,3 all have OPs/EDs/SPs/PVs, could them be marked from different seasons

**Comment by Dingmatt** [comment]
Hi,

At the moment its not possible as the agent makes use of [ZeroQI's ASS (scanner)](https://github.com/ZeroQI/Absolute-Series-Scanner) which doesn't have the functionality to split the OPs/EDs by season. Storing them anywhere other than the specials folder or using the NCOP/NCED/OP/ED naming convention will just result in them not getting detected.

I may create my own scanner at some point and could look into the possibility at that time though I wouldn't be surprised if Plex simply won't allow such a deviation from its standard naming/storage conventions.

I can see you've already raised the same question with ZeroQI, so I'd take his answer a gospel for the time being.

Regards,
