### ISSUE TITLE
Japanese Episode Titles

### ISSUE THREAD

**Issue by WeslleyNasRocha** [Dingmatt/AMSA#9]
I cant change the language of the episodes,
Anyway this can be made?

![Japanese episodes](https://user-images.githubusercontent.com/19312651/31064427-770a0a7c-a712-11e7-95f3-218c9951796c.png)

**Comment by Dingmatt** [comment]
@WeslleyNasRocha Sorry for the delay in addressing this, I'll start looking in to his now.
